### ISSUE TITLE
Run Project with Debug

### ISSUE THREAD

**Issue by deamul1sk** [saltedge/sca-identity-service-example#10]
**Summary:**  
`I'm not a Spring Boot and Kotlin expert. I'm looking to use Debug to test flow so i can ask you which IDE to use for programming?`

Looking forward to your earlier reply.
Thanks,
Deam

**Comment by ConstantinKV** [comment]
@deamul1sk please ask this question (and future short questions) in Authenticator chat. 
https://gitter.im/Salt-Edge/authenticator

**Comment by deamul1sk** [comment]
thank you very much
