### ISSUE TITLE
Identity server can only run on the default https port(443)

### ISSUE THREAD

**Issue by irons163** [saltedge/sca-identity-service-example#13]
**Summary:**  
`Summary of the problem goes here`
If spring boot identity server not run on the 443 port, then the url for QRcode is not work properly.

**Steps to reproduce:**  
1.  Change the https port from default 443 to 8443.
2.  Run spring boot identity server.
3.  Access the server by https with port 8443.
4. Click "Connect Salt Edge Authenticator", them get a QRCode.
5. Use iOS mobile authenticator to scan the QRCode, then get a url without the port 8443.

**Actual behavior:**  
`Tell us what happens instead`
Url without the port 8443.

**Expected behavior:**  
`Tell us what should happen`
Url with the port 8443.

**Comment by ConstantinKV** [comment]
Hello @irons163 

Thank you for your contribution to our project. 
Please provide us QR code screenshot or link which is encode in QR.

**Comment by ConstantinKV** [comment]
@irons163 we have noticed that current service example ignore post number while generating QR code. In a few days we will deploy major update for example application which will fix your your issue.

**Comment by irons163** [comment]
Thank you for response. I'll try it.

**Comment by ConstantinKV** [comment]
If no more questions i'll close the issue. Feel free to contact us via [Gitter chat](https://gitter.im/Salt-Edge/authenticator)
